### ISSUE TITLE
Non call rpc

### ISSUE THREAD

**Issue by root-aza** [roadrunner-php/centrifugo#5]
.rr.yaml

<details>

```yaml
version: '2.7'
rpc:
    listen: 'tcp://127.0.0.1:6001'
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
server:
    command: 'php app.php'
    relay: pipes
kv:
    local:
        driver: memory
        config:
            interval: 60
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }

centrifuge:
  proxy_address: "tcp://0.0.0.0:10001"
  grpc_api_address: "0.0.0.0:10000"


```

</details>

config.json

<details>

```json
{
    "v3_use_offset": true,
    "token_hmac_secret_key": "CPQFZIBI4vN0ha141",
    "api_key": "wDQHvgfWGye5qUvTkRMCxJra94Xp7FRZhwJYEtLz",
    "admin_password": "password",
    "admin_secret": "wDQHvgfWGye5qUvTkRMCxJra94Xp7FRZhwJYEtLz",
    "admin": true,
    "allowed_origins": [
        "*"
    ],
    "publish": true,
    "proxy_rpc": true,
    "grpc_api": true,
    "grpc_api_address": "0.0.0.0",
    "grpc_api_port": 10000,
    "proxy_rpc_endpoint": "grpc://docker.for.mac.host.internal:10001",
    "proxy_rpc_timeout": "10s",
    "uni_sse": true,
    "namespaces": [
        {
            "name": "auth",
            "anonymous": false
        }
    ]
}


```

</details>

centrifugo.php

<details>

```php
<?php

use RoadRunner\Centrifugo\Request\RequestType;

return [
   'services' => [
       RequestType::RPC->value       => \App\Module\EmptyModule\RpcCall::class
   ],
   'interceptors' => [
       RequestType::RPC->value => [
           \App\Module\EmptyModule\RpcInspector::class
       ]
   ]
];


```

</details>

Inspector

<details>

```php
<?php

declare(strict_types=1);

namespace App\Module\EmptyModule;

use Spiral\Core\CoreInterceptorInterface;
use Spiral\Core\CoreInterface;

final class RpcInspector implements CoreInterceptorInterface
{
    public function process(string $controller, string $action, array $parameters, CoreInterface $core): mixed
    {
        dumprr($controller, $action, $parameters, $parameters);

        return $core->callAction($controller, $action, $parameters);
    }
}



```

</details>

Вопрос следующего плана: почему при отключении клиента не вызывается rpc inspector/services? По идеи же должен приходить запрос на backend. proxy_publish ,proxy_subcriber работают. Может я что-то делают не так..
